apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
  namespace: kube-system
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer

