nexus:
  service:
    type: ClusterIP

persistence:
  storageClass: "gp2"
  storageSize: 1Gi

nexusBackup:
#  enabled: fals
#  imageName: quay.io/travelaudience/docker-nexus-backup
#  imageTag: 1.5.0
#  imagePullPolicy: IfNotPresent
#  env:
#    targetBucket:
#  nexusAdminPassword: "admin123"
#  persistence:
#    enabled: true
#    # existingClaim:
#    # annotations:
#    #  "helm.sh/resource-policy": keep
#    accessMode: ReadWriteOnce
#    # See comment above for information on setting the backup storageClass
#    # storageClass: "-"
#    storageClass: "	nfscsi"
    storageSize: 1Gi
#    # If PersistentDisk already exists you can create a PV for it by including the 2 following keypairs.
#    # pdName: nexus-backup-disk
#    # fsType: ext4
#  resources: {}
#    # requests:
#      # cpu: 100m
#      # memory: 256Mi
#    # limits:
#      # cpu: 200m
#      # memory: 512Mi
