services:
  tz_main:
    image: tz-main
    container_name: docker-${tz_project}
    build: ./
    platform: linux/amd64
    volumes:
      - ../../:/topzone/
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "22:22"
#      - "80:80"
#      - "8080:8080"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - "eks_project=${eks_project}"
      - "eks_domain=${eks_domain}"
      - "tz_project=${tz_project}"
      - "docker_user=${docker_user}"
      - "vault_token=${vault_token}"
